version: '3'

services:
  porch:
    build: .
    env_file: .env
    ports:
      - '3000:3000'
    links:
      - redis
  redis:
    image: redis:4
    ports:
      - '6379'
    command: redis-server --appendonly yes --requirepass porch
