version: '2'

services:
  porch:
    build: .
    volumes:
      - ./:/home/node
    ports:
      - '3000:3000'
    links:
      - mongo
  # mongodb://mongo:27017
  mongo:
    image: mongo
    ports:
      - '27017:27017'
